package test0614;

import java.sql.SQLOutput;
import java.util.Scanner;

public class Test0614 {
  public static void main(String[] args) {
//    Scanner sc = new Scanner(System.in);
    //    sc.nextInt(); // 정수를 입력해야하는데 문자열을 입력한 경우 exception 발생
    //    sc.close();

    // try-catch를 사용한 예외처리
//    try {
//      int i = sc.nextInt();
//      int result = i / 0; // ArithmeticException 발생. 숫자를 0으로 나눌 수 없어서 발생하는 예외.
//      System.out.println(result);
//    } catch (ArithmeticException e) {
//      System.out.println("0으로 나눌 수 없습니다.");
//    } finally { // 예외이든 말든 무조건 실행되는 코드
//      System.out.println("스캐너를 종료합니다.");
//      sc.close();
//    }
    //    System.out.println("정상적으로 종료되었습니다.");

    //    try {
    //      divide(10, 0);
    //    } catch (ArithmeticException E) {
    //      System.out.println("0으로 나눌 수 없습니다.");
    //    }
    //    try {
    //      divide(10, 0);
    //    } catch (ArithmeticException | NullPointerException e) { // catch를 나누는 게 더 보기 좋음
    //      System.out.println("0으로 나눌 수 없습니다.");
    //    }
    //    System.out.println("정상적으로 종료되었습니다.");
    //  }

    //  private static int divide(int a, int b) {
    //    if (a / b == 0) {
    //      throw new ArithmeticException();
    //    } else {
    //      throw new NullPointerException();
    //    }
    //  private static int divide(int a, int b) throws ArithmeticException {
    //    return a / b;
    //    // 메서드 안에서 여러 개의 예외를 throw 할 수도 있음
    //  }
//    try{
//      int[] numbrs={1,2,3};
//      System.out.println(number[5]);
//    } catch(ArrayIndexOutOfBoundsException e){
//
//    }
  }
}
